3-11

diff --git a/Proyecto1/script1 b/Proyecto1/script1
--- a/Proyecto1/script1
+++ b/Proyecto1/script1
@@ -4,7 +4,7 @@
 	#Autor : Rubén Pujante
 
 	#--------------------------------------------------------------------------------------------------------------------------
-		# ----- COLORES
+		# ----- COLORES 
 		
 			nc='\033[0m' 		#Sin color
 			r='\033[0;31m'		#Rojo
@@ -19,7 +19,7 @@
 			ADMIN_DN="cn=admin,dc=servidor25,dc=local"
 
 			separador(){
-				echo -e "${b}---------------------------------------------------------------------------${nc}"
+				echo -e "${b}---------------------------------------------------------------------------${nc}"						# ----- Separador visual	
 			}
 
 	#--------------------------------------------------------------------------------------------------------------------------
@@ -30,7 +30,7 @@
 			actualizar_paquetes(){
 				sleep 1
 		
-					echo -e "${b} Actualizando paquetes...${nc}"
+					echo -e "${b} Actualizando paquetes...${nc}"																	# ----- Update sin confirmación necesaria.
 					echo ""
 						
 						apt-get update -y 
@@ -45,7 +45,7 @@
 			instalar_paquetes(){
 				sleep 1
 				
-				export DEBIAN_FRONTEND=noninteractive
+				export DEBIAN_FRONTEND=noninteractive																				# ---- Con DEBIAN_FRONTEND conseguimos omitir el asistente de instalación de cualquier paquete que lo utilice.
 			
 					echo ""
 					echo -e "${b} Instalando paquetes necesarios...${nc}"
@@ -103,29 +103,29 @@
 									echo -e "${g} Archivo ldap.conf copiado a ldap.conf.bak${nc}"
 									echo ""
 								else
-									echo -e "${r}ERROR: No se ha podido hacer la copia de seguridad del archivo${nc}"
+									echo -e "${r}ERROR: No se ha podido hacer la copia de seguridad del archivo${nc}"				# ----- Con este bucle 'If' controlamos la creación de la copia del archivo. 
 								fi
 
 							sleep 1
 
 			# ----- Establecer DN del servidor.
-						read -p " Introduce la base(DN) del servidor.(Ej:dc=tu,dc=servidor):" BASE_DN
+						read -p " Introduce la base(DN) del servidor.(Ej:dc=tu,dc=servidor):" BASE_DN								# ----- Con read leemos la entrada del usuario para la base(DN), la respuesta se asigna a la variable BASE_DN
 
 						echo -e "${y} Estableciendo Distinguished Name (DN) base. ${nc}" $BASE_DN 
 							
 							sleep 1
-							
-								if grep -q "^base" /etc/ldap.conf; then
-									sed -i "s|^base.*|base $BASE_DN|" /etc/ldap.conf
-									echo -e "${g} Distinguished Name establecido.${nc}"
+																																	# ----- Con este bucle if modificamos el archivo ldap.conf
+								if grep -q "^base" /etc/ldap.conf; then																# ----- Con 'grep' buscamos las líneas que empiecen por base(^base) en el fichero indicado, sin mostrar dichas líneas(-q).
+									sed -i "s|^base.*|base $BASE_DN|" /etc/ldap.conf 												# ----- Con 'sed' -i(in-place) sustituimos, en las líneas que empiecen por base, seguido de lo que sea, base seguido del contenido de la variable $BASE_DN 
+									echo -e "${g} Distinguished Name establecido.${nc}"												# ----- en el fichero indicado.																
 									echo ""
-								else
+								else																							
 									echo -e "${r}ERROR: DN no establecido.${nc}"
 									echo ""	
 								fi
 								
 			# ----- Establecer URI del servidor.
-						read -p " Introduce la URI del servidor.(Ej: ldap://192.168.100.10): " LDAP_SERVER
+						read -p " Introduce la URI del servidor.(Ej: ldap://192.168.100.10): " LDAP_SERVER							# ----- El comportamiento de este bucle es similar al anterior, con el modificamos el fichero ldap.conf para introducir la dirección del servidor.
 
 						echo -e "${y} Estableciendo URI del servidor LDAP. ${nc}" $LDAP_SERVER 
 							
@@ -141,7 +141,7 @@
 								fi
 						
 			# ----- Establecer nombre usuario con privilegios del servidor.
-						read -p " Introduce el DN del ADMIN del servidor.(Ej:cn=admin,dc=tu,dc=servidor): " LDAP_SERVER
+						read -p " Introduce el DN del ADMIN del servidor.(Ej:cn=admin,dc=tu,dc=servidor): " LDAP_SERVER				# ----- Este bucle tiene el mismo comportamiento que los anteriores, en él introducimos el DN del administrador.		
 
 						echo -e "${y} Estableciendo admin del servidor LDAP. ${nc}" $ADMIN_DN 
 							
@@ -176,13 +176,12 @@
 			# ----- Copia de seguridad del archivo.
 						echo -e "${y} Haciendo copia de seguridad del archivo nsswitch.conf"
 						
-
 							sleep 1
 
 						 	cp /etc/nsswitch.conf /etc/nsswitch.conf.bak
 
 							 	if [ $? -eq 0 ]; then
-									echo -e "${g} Archivo ldap.conf copiado a nsswitch.bak${nc}"
+									echo -e "${g} Archivo ldap.conf copiado a nsswitch.bak${nc}"											# ----- Bucle para controlar la copia del archivo antes de modificarlo.
 									echo ""
 								else
 									echo -e "${r}ERROR: No se ha podido hacer la copia de seguridad del archivo${nc}"
@@ -191,7 +190,7 @@
 							sleep 1
 
 			# ----- Modificación del archivo
-						echo -e "${y} Modificando passwd...${nc}"
+						echo -e "${y} Modificando passwd...${nc}"																			# ----- Modificamos el contenido de las líneas que comiencen por lo indicado, en este caso 'passwd' por passwd:    files ldap, en el fichero.
 							sed -i 's|^passwd:.*|passwd:		files ldap|' /etc/nsswitch.conf
 							echo -e "${g} passwd modificacado${nc}"
 							echo ""
@@ -232,11 +231,11 @@
 				sleep 1
 
 			# ----- Copia de seguridad del archivo.
-						echo -e "${y} Haciendo copia de seguridad del archivo common-password"
+						echo -e "${y} Haciendo copia de seguridad del archivo common-password"												# ----- Copia del archivo
 
 						sleep 1
 						
-						cp /etc/pam.d/common-password /etc/pam.d/common-password.bak 
+						cp /etc/pam.d/common-password /etc/pam.d/common-password.bak 														# ----- Bucle control de copia correcta
 
 							if [ $? -eq 0 ]; then
 									echo -e "${g} Archivo ldap.conf copiado a common-password.bak${nc}"
@@ -245,12 +244,10 @@
 									echo -e "${r}ERROR: No se ha podido hacer la copia de seguridad del archivo${nc}"
 								fi
 
-						sleep 1
-
-				
+						sleep 1		
 
 			# ----- Modificación del archivo
-						sed -i 's/use_authtok//g' /etc/pam.d/common-password
+						sed -i 's/use_authtok//g' /etc/pam.d/common-password																# ----- Modificación del fichero, sustituyendo, en todas las líneas en las que aparezcan 'use_authtok', dicha ocurrencia por un campo vacío.
 
 				echo -e "${g} Archivo pam.d/common-password configurado con éxito${nc}"
 				echo ""
@@ -273,10 +270,10 @@
 
 						sleep 1
 
-						cp /etc/pam.d/common-session /etc/pam.d/common-session.bak 
+						cp /etc/pam.d/common-session /etc/pam.d/common-session.bak 															# ----- Copia del archivo.
 
-							if [ $? -eq 0 ]; then
-									echo -e "${g} Archivo ldap.conf copiado a common-session.bak${nc}"
+							if [ $? -eq 0 ]; then										
+									echo -e "${g} Archivo ldap.conf copiado a common-session.bak${nc}"										# ----- Bucle control copia.
 									echo ""
 								else
 									echo -e "${r}ERROR: No se ha podido hacer la copia de seguridad del archivo${nc}"
@@ -291,7 +288,7 @@
 						echo -e "${y} Añadiendo línea...${nc}"
 						sleep 1
 
-		    				sed -i '$i session optional 	pam_mkhomedir.so skel=/etc/skel umask=077' "$RUTA"
+		    				sed -i '$i session optional 	pam_mkhomedir.so skel=/etc/skel umask=077' "$RUTA"								# ----- Con sed -i '$i ...' añadimos antes de la última línea el contenido indicado.
 		    				 
 		    				echo -e "${g} Línea añadida con éxito.${nc}"
 		    				echo ""
@@ -319,12 +316,12 @@
 
 						sleep 1
 
-						cp /etc/nslcd.conf /etc/nslcd.conf.bak 
+						cp /etc/nslcd.conf /etc/nslcd.conf.bak 																					# ----- Copia del archivo
 
 						sleep 1
 
 							if [ $? -eq 0 ]; then
-								echo -e "${g} Archivo ldap.conf copiado a nslcd.bak${nc}"
+								echo -e "${g} Archivo ldap.conf copiado a nslcd.bak${nc}"														# ----- Bucle control copia.
 								echo ""
 							else
 								echo -e "${r}ERROR: No se ha podido hacer la copia de seguridad del archivo${nc}"
@@ -334,7 +331,7 @@
 					
 			# ----- Modificación del archivo.
 
-					echo -e "${y} Configurando URI${nc}"
+					echo -e "${y} Configurando URI${nc}"																						# ----- Modificamos las líneas del fichero nslcd.conf que comiencen por 'uri' y 'base' por el contenido de las variables $LDAP_SERVER y $BASE_DN
 					sed -i "s|^uri.*|uri $LDAP_SERVER|" /etc/nslcd.conf
 						echo -e "${g} URI modificada${nc}"
 						echo ""
@@ -358,7 +355,7 @@
 		
 			reinicio(){
 				echo ""
-				echo -e "${y} Reiniciando el equipo...${nc}"
+				echo -e "${y} Reiniciando el equipo...${nc}"																					# ----- Reiniciamos el equipo tras 5 segundos.
 			
 					sleep 5
 				
@@ -366,12 +363,12 @@
 			}
 	#-------------------------------------------------------------------------------------------------------------------------
 		
-		# ----- Inicialización del script.
+		# ----- Inicialización del script.																										# ----- Flujo del script
 
-			read -p "$(echo -e "${y} ¿Desea iniciar la ejecución del script para la unión del usuario al server? (s/n): ${nc}")" respuesta
+			read -p "$(echo -e "${y} ¿Desea iniciar la ejecución del script para la unión del usuario al server? (s/n): ${nc}")" respuesta		# ----- Pregunta si se desea iniciar.	
 			echo ""
 
-				if [[ "$respuesta" =~ ^[Ss]$ ]]; then
+				if [[ "$respuesta" =~ ^[Ss]$ ]]; then																							# ----- Si la respuesta es s o S comienza la ejecución, llamando a cada función encargada de cada parte del script.
 
 					actualizar_paquetes
 					
@@ -389,10 +386,10 @@
 
 					echo ""
 					echo -e "${g}  Todo listo!"
-					echo -e "  Ya puede iniciar sesión en el servidor${nc}"	
+					echo -e "  Ya puede iniciar sesión en el servidor${nc}"																		# ----- Mensaje de finalización.
 					echo ""
 					
 				else
-					echo -e "${r}Ejecución del script cancelada.${nc}"
+					echo -e "${r}Ejecución del script cancelada.${nc}"																			# ----- Si la respuesta es diferente a s o S el script no se ejecta.
 					exit 0
 				fi
